trigger:
  branches:
    include:
      - main
      - master

pr:
  branches:
    include:
      - main
      - master

pool:
  name: Default

steps:
  - script: node --version && npm --version
    displayName: 'Environment Check'

  - script: npm ci --prefer-offline
    displayName: 'Install dependencies'

  - script: npm run build
    displayName: 'Build'

  - script: npm test -- --runInBand --forceExit
    displayName: 'Test'
